import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface PDFOptions {
  title: string;
  type: "maturity" | "governance";
  organization?: string;
  industry?: string;
  overallScore: number;
  maturityLevel: string;
  domainScores: Record<string, number>;
  regionalScores?: Record<string, { score: number; max: number; pct: number }>;
}

// ── Capture results dashboard as PDF ──
export async function exportResultsToPDF(
  elementId: string,
  filename: string = "STRATRI-Assessment-Results.pdf"
): Promise<Blob | null> {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      console.error("Element not found:", elementId);
      return null;
    }

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#FEFBF8",
      logging: false,
      windowWidth: 900,
    });

    const imgData = canvas.toDataURL("image/png");
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const pdf = new jsPDF({
      orientation: imgHeight > 297 ? "portrait" : "portrait",
      unit: "mm",
      format: "a4",
    });

    // If content is taller than one page, split across pages
    const pageHeight = 297; // A4 height
    let position = 0;
    let remainingHeight = imgHeight;

    while (remainingHeight > 0) {
      if (position > 0) pdf.addPage();

      pdf.addImage(imgData, "PNG", 0, -position, imgWidth, imgHeight);
      remainingHeight -= pageHeight;
      position += pageHeight;
    }

    // Add footer
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(138, 143, 156);
      pdf.text(
        `STRATRI · AI Governance & Technology Policy Studio · ${new Date().toLocaleDateString("en-GB")}`,
        105,
        290,
        { align: "center" }
      );
      pdf.text(`${i} / ${totalPages}`, 195, 290, { align: "right" });
    }

    // Return as blob for email attachment or download
    const blob = pdf.output("blob");

    // Also trigger download
    pdf.save(filename);

    return blob;
  } catch (error) {
    console.error("PDF generation error:", error);
    return null;
  }
}

// ── Generate summary text for email body ──
export function generateResultsSummary(options: PDFOptions): string {
  const domainLines = Object.entries(options.domainScores)
    .map(([name, score]) => `  ${name}: ${score.toFixed(1)}/5.0`)
    .join("\n");

  let summary = `
STRATRI AI ${options.type === "maturity" ? "Maturity" : "Governance"} Assessment Results
${"═".repeat(56)}

Organization: ${options.organization || "—"}
Industry: ${options.industry || "—"}
Date: ${new Date().toLocaleDateString("en-GB")}

Overall Score: ${options.overallScore.toFixed(1)}/5.0
Maturity Level: ${options.maturityLevel}

Domain Scores:
${domainLines}
`;

  if (options.regionalScores && Object.keys(options.regionalScores).length > 0) {
    const regionLabels: Record<string, string> = {
      eu: "EU AI Act",
      us: "US State AI Laws",
      tr: "Türkiye KVKK",
    };

    summary += `\nRegional Compliance:\n`;
    for (const [id, rs] of Object.entries(options.regionalScores)) {
      summary += `  ${regionLabels[id] || id}: ${rs.pct}% (${rs.score}/${rs.max})\n`;
    }
  }

  summary += `
${"─".repeat(56)}
This assessment was generated by STRATRI.
For a detailed governance roadmap, contact us at hello@stratri.com
`;

  return summary;
}
